/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoestructurasgabriel.pkg1;

import javax.swing.JOptionPane;


public class Simular extends javax.swing.JFrame {

    static MyGraph graph;
    int indice;
    String[] textoCiclos ;
    String[] textoFeromonas;
    static String path;

    /**
     * Creates new form Simular
     */
    public Simular(MyGraph g, String p) {
        initComponents();
        path = p;
        this.setVisible(true);
        graph = g;
        indice = 0;
        this.jTextArea1.setText(graph.show());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textH = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ciclos = new javax.swing.JTextField();
        inicial = new javax.swing.JTextField();
        cFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ants = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gif = new javax.swing.JTextField();
        gvc = new javax.swing.JTextField();
        camino = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textF = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fef = new javax.swing.JTextField();
        verCiclos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        jLabel3.setText("SIMULAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        sim.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        sim.setText("SIMULAR");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });
        jPanel1.add(sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, -1, -1));

        textH.setEditable(false);
        textH.setColumns(20);
        textH.setRows(5);
        jScrollPane1.setViewportView(textH);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 280));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel2.setText("de feromonas (ρ):");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jButton3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, -1));

        ciclos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel1.add(ciclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 170, 40));

        inicial.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel1.add(inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, 40));

        cFinal.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel1.add(cFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 170, 40));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setText("Camino más óptimo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel5.setText("Ciudad Inicial:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel6.setText("Ciudad Final:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel7.setText("Numero de Ciclos:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, -1));

        ants.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel1.add(ants, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 170, 40));

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel8.setText("Hormigas:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        gif.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel1.add(gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 170, 40));

        gvc.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel1.add(gvc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 170, 40));

        camino.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel1.add(camino, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 450, 40));

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel11.setText("Factor de evaporacion");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel12.setText("Grado de importancia");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel13.setText("de feromonas (α):");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel14.setText("Grado de visibilidad");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel15.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel15.setText("de ciudades (β):");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        textF.setEditable(false);
        textF.setColumns(20);
        textF.setRows(5);
        jScrollPane2.setViewportView(textF);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, 280));

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel9.setText("Hormigas:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel10.setText("Rastro de feromonas:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        fef.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel1.add(fef, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 180, 40));

        verCiclos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        verCiclos.setText("SIGUIENTE CICLO");
        verCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCiclosActionPerformed(evt);
            }
        });
        jPanel1.add(verCiclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, -1, 280));

        jLabel16.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel16.setText("Ciudades:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
        // TODO add your handling code here:
        try {
            String origen = this.inicial.getText();
            String destino = this.cFinal.getText();
            int ciclos = Integer.parseInt(this.ciclos.getText());
            int hormigas = Integer.parseInt(this.ants.getText());
            double alpha = Double.parseDouble(this.gif.getText());
            double beta = Double.parseDouble(this.gvc.getText());
            double rho = Double.parseDouble(this.fef.getText());
//            System.out.println(0 <= rho);
//                System.out.println(rho < 1);
//                System.out.println(graph.searchCity(origen));
//                System.out.println(graph.searchCity(destino));
            if (0 <= rho && rho < 1 && graph.searchCity(origen) && graph.searchCity(destino)) {
                
                
                try {
                    textoCiclos = new String[ciclos];
                    textoFeromonas = new String[ciclos];
                    Ant menorRecorrido = null;
                    graph.iniciatePheromones();
                    graph.setFL(origen, destino);
                    for (int i = 0; i < ciclos; i++) {
                        String ciclo = "";
                        String fer = "";
                        for (int j = 0; j < hormigas; j++) {
                            Ant a = new Ant();
                            graph.run(a, alpha, beta, rho);
                            ciclo += "#" + j + 1 + ": Recorrido realizado: " + a.visitedCities + ". Distancia recorrida: " + a.totalDistance + "\n";
                            if (menorRecorrido == null || menorRecorrido.totalDistance > a.totalDistance) {
                                menorRecorrido = a;
                            }

                        }
                        graph.calculatePheromonesTrail(rho);
                        fer += graph.pheromones();
                        textoCiclos[i] = ciclo;
                        textoFeromonas[i] = fer;
                    }
                    this.camino.setText(menorRecorrido.visitedCities + "\nDistancia: " + menorRecorrido.totalDistance);
                    this.textH.setText(textoCiclos[0]);
                    this.textF.setText(textoFeromonas[0]);
                    if (ciclos > 1) {
                        this.sim.setEnabled(false);
                        this.verCiclos.setEnabled(true);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "VALORES ERRONEOS");
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "VALORES ERRONEOS");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "VALORES ERRONEOS");
        }


    }//GEN-LAST:event_simActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal vp = new VentanaPrincipal(graph,path);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void verCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCiclosActionPerformed
        // TODO add your handling code here:
        this.textH.setText(textoCiclos[indice]);
        this.textF.setText(textoFeromonas[indice]);
        indice++;
        if (indice+1 == textoCiclos.length) {
            this.sim.setEnabled(true);
            this.verCiclos.setEnabled(false);
        }
    }//GEN-LAST:event_verCiclosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simular(graph, path).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ants;
    private javax.swing.JTextField cFinal;
    private javax.swing.JTextField camino;
    private javax.swing.JTextField ciclos;
    private javax.swing.JTextField fef;
    private javax.swing.JTextField gif;
    private javax.swing.JTextField gvc;
    private javax.swing.JTextField inicial;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton sim;
    private javax.swing.JTextArea textF;
    private javax.swing.JTextArea textH;
    private javax.swing.JButton verCiclos;
    // End of variables declaration//GEN-END:variables
}
